#!/usr/bin/env bash
# Create — once — a stable, self-signed code-signing certificate in the login keychain, so every local
# build of Dev Monitor is signed with the SAME identity.
#
# Why this exists:
#   macOS ties TCC permission grants (Downloads, Music, Automation, …) to an app's code-signing
#   identity. Dev Monitor is ad-hoc signed (CODE_SIGN_IDENTITY = "-"), and an ad-hoc signature carries
#   NO stable identity — TCC falls back to the cdhash, which changes on *every* build. So each reinstall
#   looks like a brand-new app and macOS re-prompts for all permissions.
#
#   Signing with a persistent self-signed cert gives the app a stable "designated requirement"
#   (identifier + leaf-cert hash). Grant the permissions once and every future build signed with this
#   cert keeps them.
#
# The cert is local-only and self-signed: it authorizes nothing off this machine. It exists purely to
# keep the signing identity — and therefore the TCC grants — stable across rebuilds.
#
# Idempotent: does nothing if the identity already exists. Prints the identity name on stdout.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CERT_CN="Dev Monitor Local Signing"
KEYCHAIN="${LOGIN_KEYCHAIN:-$HOME/Library/Keychains/login.keychain-db}"
LOCAL_XCCONFIG="$ROOT/tools/Signing.local.xcconfig"

# Point every local build at the cert by writing the git-ignored override that tools/Signing.xcconfig
# pulls in via `#include?`. Idempotent. This is what makes a plain `xcodebuild` (Xcode Run, the install
# script, any other flow) sign with the stable identity — not just tools/install-local.sh.
write_local_xcconfig() {
  local want="CODE_SIGN_IDENTITY = $CERT_CN"
  if [ ! -f "$LOCAL_XCCONFIG" ] || ! grep -qF "$want" "$LOCAL_XCCONFIG"; then
    printf '// Auto-generated by tools/ensure-signing-cert.sh — git-ignored, this machine only.\n%s\n' \
      "$want" > "$LOCAL_XCCONFIG"
    echo "Wrote $LOCAL_XCCONFIG" >&2
  fi
}

# Already present? Reuse it — a freshly generated cert would change the leaf hash and defeat the point.
# NB: no -v here. A self-signed cert is "not trusted", so `find-identity -v` (valid only) hides it —
# but codesign can still sign with it, and reusing the SAME cert is exactly what keeps the hash stable.
if security find-identity -p codesigning "$KEYCHAIN" 2>/dev/null | grep -qF "$CERT_CN"; then
  write_local_xcconfig
  echo "$CERT_CN"
  exit 0
fi

echo "Creating self-signed code-signing certificate \"$CERT_CN\" in the login keychain…" >&2
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

cat > "$TMP/codesign.cnf" <<CNF
[ req ]
distinguished_name = dn
x509_extensions    = v3
prompt             = no
[ dn ]
CN = $CERT_CN
[ v3 ]
basicConstraints = critical, CA:false
keyUsage         = critical, digitalSignature
extendedKeyUsage = critical, codeSigning
CNF

# Key + self-signed cert (10-year validity), then bundle into a PKCS#12.
openssl req -x509 -newkey rsa:2048 -nodes -days 3650 \
  -keyout "$TMP/key.pem" -out "$TMP/cert.pem" \
  -config "$TMP/codesign.cnf" -extensions v3 >/dev/null 2>&1

# macOS `security import` only reads legacy-encrypted PKCS#12 (3DES/SHA-1). OpenSSL 3 defaults to
# AES-256/SHA-256, which fails to import ("MAC verification failed"), so pass -legacy when supported;
# LibreSSL already emits the legacy format and rejects the flag, so fall back without it. A non-empty
# transient password is required — the empty-password MAC is what trips up the importer.
P12_PASS="devmonitor-local"
openssl pkcs12 -export -legacy -inkey "$TMP/key.pem" -in "$TMP/cert.pem" \
      -name "$CERT_CN" -out "$TMP/cert.p12" -passout "pass:$P12_PASS" >/dev/null 2>&1 \
  || openssl pkcs12 -export -inkey "$TMP/key.pem" -in "$TMP/cert.pem" \
      -name "$CERT_CN" -out "$TMP/cert.p12" -passout "pass:$P12_PASS" >/dev/null 2>&1

# -T /usr/bin/codesign puts codesign on the private key's access list. macOS still gates the key with
# a partition list, so the FIRST build will pop ONE keychain dialog — click "Always Allow" and you
# won't see it again.
security import "$TMP/cert.p12" -k "$KEYCHAIN" -P "$P12_PASS" -T /usr/bin/codesign >/dev/null

write_local_xcconfig
echo "$CERT_CN"
